version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    assignees:
      - na1307
    pull-request-branch-name:
      separator: _
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Asia/Seoul
    assignees:
      - na1307
    pull-request-branch-name:
      separator: _

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      timezone: Asia/Seoul
    assignees:
      - na1307
    pull-request-branch-name:
      separator: _
