name: GitHub Pages Blazor WASM
description: Prepare Blazor WASM for GitHub Pages

branding:
  icon: layout
  color: purple

inputs:
  project-path:
    description: Path of project (.csproj)
    required: true
  publish-path:
    description: Path to output in Publish step
    default: _out
  main-repo:
    description:
      Set to true only when running this action from the default GitHub Pages
      repository ({ID}.github.io).
    deprecationMessage: This input is deprecated. This input no longer has any effect.
    default: 'false'
  fix-404:
    description:
      Whether to apply repository-specific modifications to 404.html as well.
      This only takes effect when main-repo is false.
    deprecationMessage: This input is deprecated. This input no longer has any effect.
    default: 'true'

outputs:
  wwwroot-path:
    description: Path of wwwroot

runs:
  using: node20
  main: dist/index.js
