name: GitHub Pages Blazor WASM
description: Prepare Blazor WASM for GitHub Pages

branding:
  icon: layout
  color: purple

inputs:
  project-path:
    description: Path of project (.csproj)
    required: true
  publish-path:
    description: Path to output in Publish step
    default: _out
  gh-token:
    description: The GitHub Token.
    default: ${{ github.token }}

outputs:
  wwwroot-path:
    description: Path of wwwroot

runs:
  using: node24
  main: dist/index.js
