name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-non-main-repo-with-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: false
      with-404: true

  test-main-repo-with-404:
    uses: ./.github/workflows/test-core.yml
    with:
      mock-repo: na1307/na1307.github.io
      main-repo: true
      with-404: true

  test-non-main-repo-without-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: false
      with-404: false

  test-main-repo-without-404:
    uses: ./.github/workflows/test-core.yml
    with:
      mock-repo: na1307/na1307.github.io
      main-repo: true
      with-404: false
