name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-non-main-repo-fix-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: false
      fix-404: true

  test-main-repo-fix-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: true
      fix-404: true

  test-non-main-repo-no-fix-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: false
      fix-404: false

  test-main-repo-no-fix-404:
    uses: ./.github/workflows/test-core.yml
    with:
      main-repo: true
      fix-404: false
