name: Test Core

on:
  workflow_call:
    inputs:
      mock-repo:
        required: false
        type: string
      main-repo:
        required: true
        type: boolean
      with-404:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Override GITHUB_REPOSITORY
        if: ${{ inputs.mock-repo }}
        run: |
          echo "Simulating a different repository"
          echo "GITHUB_REPOSITORY=${{ inputs.mock-repo }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: GitHub Pages Blazor WASM
        uses: ./
        with:
          project-path: Test/Test.csproj
      - name: Delete 404
        if: ${{ inputs.with-404 == false }}
        run: rm -f _out/wwwroot/404.html
      - name: Verify
        run: Test/Verify.sh --main-repo=${{ inputs.main-repo }} ${{ github.event.repository.name }}
